all:
	g++ quick-union-by-rank-with-path-compression.cpp ../data-structures/UnionFind.cpp -o quick-union-by-rank-with-path-compression.o -Wall

run:
	./quick-union-by-rank-with-path-compression.o

clean: 
	$(RM) *.o